services:
  server:
    build: ./server
    container_name: pollserver
    ports:
      - "5000:5000"
    depends_on:
      - db
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=polldb
      - POSTGRES_HOST=db
      - POSTGRES_PORT=5432
      - COOKIE_SECRET=DKSFJSDJAjskdjflsjdkfjsdosgijejg
      - JWT_SECRET=SDGLKSLJGAKSOGISDGBGB654645
  client:
    build:
      context: ./client
      args:
        NEXT_PUBLIC_SERVER_URL: http://localhost:5000
    container_name: pollclient
    ports:
      - "3000:3000"
    environment:
      - NEXT_PUBLIC_SERVER_URL=http://localhost:5000
    depends_on:
      - server
      - db
  db:
    image: postgres:15-alpine
    container_name: polldb
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: polldb
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db-data:
    driver: local

networks:
  default:
    driver: bridge
